# Site settings
title: "Common Data Format Test Method"
description: "An executable test method for NIST Voting Common Data Formats"

baseurl: "/cdf-test-method" # the subpath of your site, e.g. /blog
url: "https://pages.nist.gov/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

exclude:
- ".ruby-version"
- ".jekyll-metadata"
- ".gitignore"
- ".travis.yml"
- todo.txt
- resources
- Gemfile
- Gemfile.lock
- Makefile
- vendor
- README.md
- CONTRIBUTING.md
- LICENSE.md

# GitHub information
org_name: usnistgov
repo_name: cdf-test-method

# Navigation
# List links that should appear in the site sidebar here
navigation:
- text: Home
  url: /cdf-test-method/
- text: Usage
  url: /cdf-test-method/USAGE.html
- text: Reporting
  url: /cdf-test-method/REPORT.html
- text: FAQ
  url: /cdf-test-method/FAQ.html
- text: Protocol
  url: /cdf-test-method/PROTOCOL.md

host: 0.0.0.0